# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/github/Embedded-System-Design-Flow-on-Zynq/labsolutions/embedded/2018_2_pynq_z2_labsolution/lab2/lab2.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github/Embedded-System-Design-Flow-on-Zynq/labsolutions/embedded/2018_2_pynq_z2_labsolution/lab2/lab2.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/github/Embedded-System-Design-Flow-on-Zynq/labsolutions/embedded/2018_2_pynq_z2_labsolution/lab2/lab2.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
# IP: The module: 'system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github/Embedded-System-Design-Flow-on-Zynq/labsolutions/embedded/2018_2_pynq_z2_labsolution/lab2/lab2.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
